// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/send": {
            "post": {
                "description": "Принимает полное сообщение от прикладного уровня и отправляет его целиком на агентный уровень (без разбиения на сегменты)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transport"
                ],
                "summary": "Передать сообщение от прикладного уровня на агентный уровень",
                "parameters": [
                    {
                        "description": "Полное сообщение от пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сообщение успешно передано",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Ошибка при передаче на агентный уровень",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transfer": {
            "post": {
                "description": "Принимает сегмент от агента и сохраняет для последующей сборки",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transport"
                ],
                "summary": "Принять сегмент от агентного уровня",
                "parameters": [
                    {
                        "description": "Сегмент сообщения",
                        "name": "segment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сегмент принят",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Текст ошибки",
                    "type": "string",
                    "example": "invalid json"
                }
            }
        },
        "models.SendRequest": {
            "description": "Полное сообщение, которое транспортный уровень передаёт агентному уровню без изменений",
            "type": "object",
            "properties": {
                "data": {
                    "description": "Текст сообщения",
                    "type": "string",
                    "example": "Привет, как дела?"
                },
                "send_time": {
                    "description": "Время отправки",
                    "type": "string",
                    "example": "2025-03-29T12:00:00Z"
                },
                "username": {
                    "description": "Отправитель",
                    "type": "string",
                    "example": "alice"
                }
            }
        },
        "models.SuccessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Статус операции",
                    "type": "string",
                    "example": "accepted"
                }
            }
        },
        "models.TransferRequest": {
            "description": "Сегмент разбитого сообщения",
            "type": "object",
            "properties": {
                "payload": {
                    "description": "Данные сегмента",
                    "type": "string",
                    "example": "часть текста..."
                },
                "segment_number": {
                    "description": "Номер сегмента (с 1)",
                    "type": "integer",
                    "example": 1
                },
                "send_time": {
                    "description": "Время отправки (ID сообщения)",
                    "type": "string",
                    "example": "2025-03-29T12:00:00Z"
                },
                "total_segments": {
                    "description": "Всего сегментов в сообщении",
                    "type": "integer",
                    "example": 5
                },
                "username": {
                    "description": "Имя отправителя",
                    "type": "string",
                    "example": "alice"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Transport Layer API",
	Description:      "API транспортного уровня для обмена сообщениями между прикладным и агентным уровнями.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
