// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/segment": {
            "post": {
                "description": "Принимает один сегмент сообщения. В реальной реализации здесь должна быть отправка в Kafka, потеря с вероятностью R% и т.д. В данной заглушке просто возвращается 200 OK.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transport"
                ],
                "summary": "Принять сегмент от агента",
                "parameters": [
                    {
                        "description": "Данные сегмента",
                        "name": "segment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Segment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Сегмент принят (заглушка)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Segment": {
            "type": "object",
            "properties": {
                "payload": {
                    "description": "Полезная нагрузка (часть сообщения)",
                    "type": "string",
                    "example": "часть текста..."
                },
                "segment_number": {
                    "description": "Номер сегмента в сообщении",
                    "type": "integer",
                    "example": 1
                },
                "send_time": {
                    "description": "Время отправки (идентификатор сообщения)",
                    "type": "string",
                    "example": "2025-03-12T10:00:00Z"
                },
                "total_segments": {
                    "description": "Общее количество сегментов",
                    "type": "integer",
                    "example": 5
                },
                "username": {
                    "description": "Имя отправителя",
                    "type": "string",
                    "example": "alice"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Transport Layer API (Stub)",
	Description:      "Заглушка транспортного уровня для демонстрации Swagger.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
